exclude:
  - .jekyll-cache
incremental: false
use-assets-cdn: true
sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
scholar:
  style: /_bibliography/acm-short.csl
  locale: en
  sort_by: year,authors,title
  order: descending
  bibtex_filters: 
    - latex
    - smallcaps
    - superscript
  bibtex_skip_fields: 
    - abstract
    - groups
    - report
    - type
  bibliography_template: bib_reference
url: "https://bigraphs.github.io"
baseurl: "/jlibbig"
title: "jLibBig"
timezone: Europe/Rome
encoding: utf-8
lang: en
google_analytics: "G-8KP513LJEV"
keywords: 
  - bigraphs
  - "bigraphical reactive systems"
  - BRS
  - "graph rewriting"
  - "graph transformation"